import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NavBar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="grid grid-rows-[auto_1fr] min-h-screen bg-gray-200">
          {/* Barra de navegação (fica no topo) */}
          <NavBar />
          <div className="grid grid-cols-[350px_1fr] min-h-0 flex-1 p-5 gap-5">
            <Sidebar />
            <main className="p-5 overflow-y-auto rounded-2xl bg-white ">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
